USE ReqManager
GO

CREATE TRIGGER PROJ.GenerateCodeProject
ON PROJ.PROJECT
AFTER INSERT
AS
BEGIN
	BEGIN TRY
		BEGIN TRANSACTION;

UPDATE PROJ.PROJECT SET code = (SELECT 'PRJ' + CONVERT(nvarchar, MAX(P.ProjectID))
FROM PROJ.PROJECT AS P) WHERE ProjectID = (SELECT ProjectID from inserted)

		COMMIT TRANSACTION;
	END TRY
BEGIN CATCH
	SELECT
        ERROR_NUMBER() as ErrorNumber,
        ERROR_MESSAGE() as ErrorMessage;
        ROLLBACK TRANSACTION;
END CATCH
END
GO

CREATE TRIGGER TASK.GenerateCodeTask
ON TASK.TASK
AFTER INSERT
AS
BEGIN
	BEGIN TRY
		BEGIN TRANSACTION;

UPDATE TASK.TASK SET code = (SELECT 'T' + CONVERT(nvarchar, MAX(T.TaskID))
FROM TASK.TASK AS T) WHERE TaskID = (SELECT TaskID from inserted)

		COMMIT TRANSACTION;
	END TRY
BEGIN CATCH
	SELECT
        ERROR_NUMBER() as ErrorNumber,
        ERROR_MESSAGE() as ErrorMessage;
        ROLLBACK TRANSACTION;
END CATCH
END
GO

CREATE TRIGGER TASK.GenerateCodeSubtask
ON TASK.SUBTASK
AFTER INSERT
AS
BEGIN
	BEGIN TRY
		BEGIN TRANSACTION;

UPDATE TASK.SUBTASK SET code = (SELECT 'ST' + CONVERT(nvarchar, MAX(T.SubtaskID))
FROM TASK.SUBTASK AS T) WHERE SubtaskID = (SELECT SubtaskID from inserted)

		COMMIT TRANSACTION;
	END TRY
BEGIN CATCH
	SELECT
        ERROR_NUMBER() as ErrorNumber,
        ERROR_MESSAGE() as ErrorMessage;
        ROLLBACK TRANSACTION;
END CATCH
END
GO

CREATE TRIGGER REQ.GenerateCodeRequirement
ON REQ.REQUIREMENT
AFTER INSERT
AS
BEGIN
	BEGIN TRY
		BEGIN TRANSACTION;

UPDATE REQ.REQUIREMENT SET code = (SELECT 'REQ' + CONVERT(nvarchar, MAX(R.RequirementID))
FROM REQ.REQUIREMENT AS R) WHERE RequirementID = (SELECT RequirementID from inserted)

		COMMIT TRANSACTION;
	END TRY
BEGIN CATCH
	SELECT
        ERROR_NUMBER() as ErrorNumber,
        ERROR_MESSAGE() as ErrorMessage;
        ROLLBACK TRANSACTION;
END CATCH
END
GO

CREATE TRIGGER PROJ.GenerateCodeProjectArtifact
ON PROJ.PROJECT_ARTIFACT
AFTER INSERT
AS
BEGIN
	BEGIN TRY
		BEGIN TRANSACTION;

UPDATE PROJ.PROJECT_ARTIFACT SET code = (SELECT 'ART' + CONVERT(nvarchar, MAX(A.ProjectArtifactID))
FROM PROJ.PROJECT_ARTIFACT AS A) WHERE ProjectArtifactID = (SELECT ProjectArtifactID from inserted)

		COMMIT TRANSACTION;
	END TRY
BEGIN CATCH
	SELECT
        ERROR_NUMBER() as ErrorNumber,
        ERROR_MESSAGE() as ErrorMessage;
        ROLLBACK TRANSACTION;
END CATCH
END
GO

CREATE TRIGGER LINK.GenerateCodeLinkRequirementsArtifacts
ON LINK.LINK_BETWEEN_REQUIREMENTS_ARTIFACTS
AFTER INSERT
AS
BEGIN
	BEGIN TRY
		BEGIN TRANSACTION;

UPDATE LINK.LINK_BETWEEN_REQUIREMENTS_ARTIFACTS SET code = (SELECT 'R-A' + CONVERT(nvarchar, MAX(A.LinkArtifactRequirementID))
FROM LINK.LINK_BETWEEN_REQUIREMENTS_ARTIFACTS AS A) WHERE LinkArtifactRequirementID = (SELECT LinkArtifactRequirementID from inserted)

		COMMIT TRANSACTION;
	END TRY
BEGIN CATCH
	SELECT
        ERROR_NUMBER() as ErrorNumber,
        ERROR_MESSAGE() as ErrorMessage;
        ROLLBACK TRANSACTION;
END CATCH
END
GO

CREATE TRIGGER LINK.GenerateCodeLinkBetweenArtifacts
ON LINK.LINK_BETWEEN_REQUIREMENT
AFTER INSERT
AS
BEGIN
	BEGIN TRY
		BEGIN TRANSACTION;

UPDATE LINK.LINK_BETWEEN_REQUIREMENT SET code = (SELECT 'R-R' + CONVERT(nvarchar, MAX(A.LinkRequirementsID))
FROM LINK.LINK_BETWEEN_REQUIREMENT AS A) WHERE LinkRequirementsID = (SELECT LinkRequirementsID from inserted)

		COMMIT TRANSACTION;
	END TRY
BEGIN CATCH
	SELECT
        ERROR_NUMBER() as ErrorNumber,
        ERROR_MESSAGE() as ErrorMessage;
        ROLLBACK TRANSACTION;
END CATCH
END
GO

INSERT INTO ACCESS.USERS
SELECT 'Admin System', 'Admin', '63-43-8E-03-E7-26-E1-9C-AB-F2-7A-55-C8-03-B1-1D', 'fhkp42KdHp', 'reqmanager@gmail.com', 'admin', '05-03-1994', 'Manager', '9999999999', 1