//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReqManager.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("PROJECT_REQUIREMENTS", Schema = "PROJ")]
    public class PROJECT_REQUIREMENTS
    {
        public PROJECT_REQUIREMENTS()
        {
            this.StakeholderRequirement = new HashSet<STAKEHOLDER_REQUIREMENT>();
            this.Task = new HashSet<TASK>();
        }
    
        [Key]
        public int ProjectRequirementID { get; set; }
        public DateTime creationDate { get; set; }
        public bool traceable { get; set; }
    
        public virtual USERS Users { get; set; }
        public virtual PROJECT Project { get; set; }
        public virtual ICollection<STAKEHOLDER_REQUIREMENT> StakeholderRequirement { get; set; }
        public virtual ICollection<TASK> Task { get; set; }
        public virtual REQUIREMENT Requirement { get; set; }
    }
}
