//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReqManager.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("PROJECT_REQUIREMENTS", Schema = "PROJ")]
    public class ProjectRequirements
    {
        public ProjectRequirements()
        {
            this.StakeholderRequirement = new HashSet<StakeholderRequirement>();
            this.Task = new HashSet<Task>();
        }
    
        [Key]
        public int ProjectRequirementID { get; set; }
        public int CreationUserID { get; set; }
        [Index("IX_PROJECT_REQUIREMENTS", 1, IsUnique = true)]
        public int ProjectID { get; set; }
        [Index("IX_PROJECT_REQUIREMENTS", 2, IsUnique = true)]
        public int RequirementID { get; set; }
        public DateTime creationDate { get; set; }
        public bool traceable { get; set; }

        [ForeignKey("CreationUserID")]
        public virtual Users Users { get; set; }
        public virtual Project Project { get; set; }
        public virtual ICollection<StakeholderRequirement> StakeholderRequirement { get; set; }
        public virtual ICollection<Task> Task { get; set; }
        public virtual Requirement Requirement { get; set; }
    }
}
