//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReqManager.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("REQUIREMENT_TYPE", Schema = "REQ")]
    public class REQUIREMENT_TYPE
    {
        public REQUIREMENT_TYPE()
        {
            this.Requirement = new HashSet<REQUIREMENT>();
            this.RequirementRationale = new HashSet<REQUIREMENT_RATIONALE>();
            this.RequirimentTemplate = new HashSet<REQUIREMENT_TEMPLATE>();
        }
    
        [Key]
        public int RequirementTypeID { get; set; }
        [MinLength(5)]
        [MaxLength(50)]
        public string description { get; set; }
    
        public virtual ICollection<REQUIREMENT> Requirement { get; set; }
        public virtual ICollection<REQUIREMENT_RATIONALE> RequirementRationale { get; set; }
        public virtual ICollection<REQUIREMENT_TEMPLATE> RequirimentTemplate { get; set; }
    }
}
