//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReqManager.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("REQUIREMENT_TYPE", Schema = "REQ")]
    public class RequirementType
    {
        public RequirementType()
        {
            this.Requirement = new HashSet<Requirement>();
            this.RequirementRationale = new HashSet<RequirementRationale>();
            this.RequirimentTemplate = new HashSet<RequirementTemplate>();
        }
    
        [Key]
        public int RequirementTypeID { get; set; }
        [MinLength(5)]
        [MaxLength(50)]
        public string description { get; set; }
    
        public virtual ICollection<Requirement> Requirement { get; set; }
        public virtual ICollection<RequirementRationale> RequirementRationale { get; set; }
        public virtual ICollection<RequirementTemplate> RequirimentTemplate { get; set; }
    }
}
