//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReqManager.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("STAKEHOLDERS", Schema = "PROJ")]
    public class STAKEHOLDERS
    {
        public STAKEHOLDERS()
        {
            this.StakeHolderRequirement = new HashSet<STAKEHOLDER_REQUIREMENT>();
            this.StakeHoldersProject = new HashSet<STAKEHOLDERS_PROJECT>();
        }
    
        [Key]
        public int StakeholderID { get; set; }
    
        public virtual USERS Users { get; set; }
        public virtual ICollection<STAKEHOLDER_REQUIREMENT> StakeHolderRequirement { get; set; }
        public virtual STAKEHOLDER_CLASSIFICATION StakeHolderClassification { get; set; }
        public virtual ICollection<STAKEHOLDERS_PROJECT> StakeHoldersProject { get; set; }
    }
}
