//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReqManager.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("STAKEHOLDERS", Schema = "PROJ")]
    public class Stakeholders
    {
        public Stakeholders()
        {
            this.StakeHolderRequirement = new HashSet<StakeholderRequirement>();
            this.StakeHoldersProject = new HashSet<StakeholdersProject>();
        }
    
        [Key]
        public int StakeholderID { get; set; }
        public int UserID { get; set; }        
        public int ClassificationID { get; set; }

        public virtual Users Users { get; set; }
        public virtual ICollection<StakeholderRequirement> StakeHolderRequirement { get; set; }
        public virtual StakeholderClassification StakeHolderClassification { get; set; }
        public virtual ICollection<StakeholdersProject> StakeHoldersProject { get; set; }
    }
}
