//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReqManager.Model
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("STAKEHOLDER_CLASSIFICATION", Schema = "PROJ")]
    public class StakeholderClassification
    {
        public StakeholderClassification()
        {
            this.StakeHolders = new HashSet<Stakeholders>();
        }
    
        [Key]
        public int ClassificationID { get; set; }
        [MinLength(6)]
        [MaxLength(50)]
        [Index(IsUnique = true)]
        public string description { get; set; }
    
        public virtual ICollection<Stakeholders> StakeHolders { get; set; }
    }
}
