//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReqManager.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("TASK", Schema = "TASK")]
    public class TASK
    {
        public TASK()
        {
            this.HistoryTask = new HashSet<HISTORY_TASK>();
            this.UserTask = new HashSet<USER_TASK>();
        }
    
        [Key]
        public int TaskID { get; set; }
        public System.DateTime creationDate { get; set; }
        [MinLength(3)]
        [MaxLength(1000)]
        [Required]
        public string description { get; set; }
        public System.DateTime startDate { get; set; }
        public Nullable<DateTime> endDate { get; set; }
    
        public virtual USERS Users { get; set; }
        public virtual PROJECT_REQUIREMENTS ProjectRequirements { get; set; }
        public virtual MEASURE_IMPORTANCE MeasureImportance { get; set; }
        public virtual ICollection<HISTORY_TASK> HistoryTask { get; set; }
        public virtual STATUS_TASK StatusTask { get; set; }
        public virtual TASK_TYPE_TEMPLATE TaskTypeTemplate { get; set; }
        public virtual TASK_TYPE TaskType { get; set; }
        public virtual ICollection<USER_TASK> UserTask { get; set; }
    }
}
