//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReqManager.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("TASK_TYPE", Schema = "TASK")]
    public  class TASK_TYPE
    {
        public TASK_TYPE()
        {
            this.Task = new HashSet<TASK>();
            this.TaskTypeTemplate = new HashSet<TASK_TYPE_TEMPLATE>();
        }
    
        [Key]
        public int TypeTaskID { get; set; }
        [Required]
        [MinLength(5)]
        [MaxLength(50)]
        public string description { get; set; }
    
        public virtual ICollection<TASK> Task { get; set; }
        public virtual ICollection<TASK_TYPE_TEMPLATE> TaskTypeTemplate { get; set; }
    }
}
